use std::fs;
use std::path::Path;

const STUB_SECRET_KEY: &str = "// Placeholder regenerated by build_secrets.py during installer build.\n\
// Decryption with this stub will fail at runtime by design.\n\n\
pub(crate) const K1: [u8; 32] = [0u8; 32];\n\
pub(crate) const K2: [u8; 32] = [0u8; 32];\n\
pub(crate) const K3: [u8; 32] = [0u8; 32];\n\n\
pub(crate) fn recover() -> [u8; 32] {\n    \
    let mut out = [0u8; 32];\n    \
    let mut i = 0;\n    \
    while i < 32 {\n        \
        out[i] = K1[i] ^ K2[i] ^ K3[i];\n        \
        i += 1;\n    \
    }\n    \
    out\n\
}\n";

fn main() {
    let key_path = Path::new("src/secret_key.rs");
    if !key_path.exists() {
        fs::write(key_path, STUB_SECRET_KEY).expect("write secret_key.rs stub");
    }
    println!("cargo:rerun-if-changed=src/secret_key.rs");
    tauri_build::build()
}
