#!/usr/bin/env python3
"""Encrypt runtime secrets (.env) into a binary blob bundled by Tauri.

Generates two artifacts:

* ``src-tauri/src/secret_key.rs`` — three 32-byte XOR-split key shares. Only
  when XOR'd together at runtime do they reconstruct the real AES-256 key,
  which keeps the key out of the compiled binary's ``strings`` output.
* ``src-tauri/resources/runtime/secrets.enc`` — AES-256-GCM ciphertext of
  the ``.env`` file, prefixed with the 12-byte nonce. Bundled as a Tauri
  resource and decrypted at runtime just before spawning sidecars.

The inputs to this script are loaded from the developer's local ``.env``
and never persisted outside the encrypted blob.
"""
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
KEY_RS_PATH = ROOT / "src-tauri" / "src" / "secret_key.rs"
ENC_PATH = ROOT / "src-tauri" / "resources" / "runtime" / "secrets.enc"


def _format_byte_array(name: str, data: bytes) -> str:
    assert len(data) == 32
    body = ", ".join(f"0x{b:02X}" for b in data)
    return f"pub(crate) const {name}: [u8; 32] = [{body}];\n"


def _write_secret_key_rs(key: bytes) -> None:
    k1 = secrets.token_bytes(32)
    k2 = secrets.token_bytes(32)
    k3 = bytes(a ^ b ^ c for a, b, c in zip(key, k1, k2))

    content = (
        "// AUTO-GENERATED by build_secrets.py. DO NOT EDIT. DO NOT COMMIT.\n"
        "// The three constants XOR together reconstruct the AES-256 key\n"
        "// that decrypts resources/runtime/secrets.enc at runtime.\n\n"
    )
    content += _format_byte_array("K1", k1)
    content += _format_byte_array("K2", k2)
    content += _format_byte_array("K3", k3)
    content += (
        "\n"
        "pub(crate) fn recover() -> [u8; 32] {\n"
        "    let mut out = [0u8; 32];\n"
        "    let mut i = 0;\n"
        "    while i < 32 {\n"
        "        out[i] = K1[i] ^ K2[i] ^ K3[i];\n"
        "        i += 1;\n"
        "    }\n"
        "    out\n"
        "}\n"
    )

    KEY_RS_PATH.parent.mkdir(parents=True, exist_ok=True)
    KEY_RS_PATH.write_text(content, encoding="utf-8")


def _encrypt_env(key: bytes, env_bytes: bytes) -> bytes:
    nonce = secrets.token_bytes(12)
    cipher = AESGCM(key)
    ciphertext = cipher.encrypt(nonce, env_bytes, associated_data=None)
    return nonce + ciphertext


def _ensure_db_key() -> None:
    """Generate DB_ENCRYPTION_KEY in .env if missing.

    The key must be stable across builds so existing SQLCipher databases stay
    readable. We only append when absent; never overwrite a user-set value.
    """
    text = ENV_PATH.read_text(encoding="utf-8")
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("DB_ENCRYPTION_KEY="):
            value = stripped.split("=", 1)[1].strip().strip('"').strip("'")
            if value:
                return
    key_hex = secrets.token_bytes(32).hex()
    separator = "" if text.endswith("\n") or not text else "\n"
    ENV_PATH.write_text(text + separator + f"DB_ENCRYPTION_KEY={key_hex}\n", encoding="utf-8")
    print("   DB_ENCRYPTION_KEY gerado e adicionado ao .env.")


def build_secrets() -> None:
    if not ENV_PATH.exists():
        raise FileNotFoundError(
            f".env nao encontrado em {ENV_PATH}. Crie o arquivo antes de gerar o instalador."
        )

    _ensure_db_key()

    env_bytes = ENV_PATH.read_bytes()
    if not env_bytes.strip():
        raise ValueError(f".env em {ENV_PATH} esta vazio.")

    key = secrets.token_bytes(32)
    _write_secret_key_rs(key)

    ENC_PATH.parent.mkdir(parents=True, exist_ok=True)
    ENC_PATH.write_bytes(_encrypt_env(key, env_bytes))

    print(f"== Segredos cifrados ==")
    print(f"   Chave dividida:   {KEY_RS_PATH.relative_to(ROOT)}")
    print(f"   Blob ciphertext:  {ENC_PATH.relative_to(ROOT)}  ({len(env_bytes)} -> {ENC_PATH.stat().st_size} bytes)")


def main() -> None:
    try:
        build_secrets()
    except Exception as error:  # noqa: BLE001
        print(f"build_secrets falhou: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
